name: pylons_flutter
description: Pylons client-side SDK
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  sacco: ^0.2.0
  dartz: ^0.10.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 5.0.16

flutter:


